/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSalaryRouteImport } from './routes/app.salary'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppAiRobotRouteImport } from './routes/app.ai-robot'
import { Route as AppWithdrawalIncomeRouteImport } from './routes/app.withdrawal.income'
import { Route as AppWithdrawalCapitalRouteImport } from './routes/app.withdrawal.capital'
import { Route as AppTeamLevel3RouteImport } from './routes/app.team.level-3'
import { Route as AppTeamLevel2RouteImport } from './routes/app.team.level-2'
import { Route as AppTeamLevel1RouteImport } from './routes/app.team.level-1'
import { Route as AppTeamDirectRouteImport } from './routes/app.team.direct'
import { Route as AppHistoryTeamRouteImport } from './routes/app.history.team'
import { Route as AppHistoryPassiveRouteImport } from './routes/app.history.passive'
import { Route as AppHistoryDirectRouteImport } from './routes/app.history.direct'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRobotRoute = AppAiRobotRouteImport.update({
  id: '/ai-robot',
  path: '/ai-robot',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawalIncomeRoute = AppWithdrawalIncomeRouteImport.update({
  id: '/withdrawal/income',
  path: '/withdrawal/income',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawalCapitalRoute = AppWithdrawalCapitalRouteImport.update({
  id: '/withdrawal/capital',
  path: '/withdrawal/capital',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamLevel3Route = AppTeamLevel3RouteImport.update({
  id: '/team/level-3',
  path: '/team/level-3',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamLevel2Route = AppTeamLevel2RouteImport.update({
  id: '/team/level-2',
  path: '/team/level-2',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamLevel1Route = AppTeamLevel1RouteImport.update({
  id: '/team/level-1',
  path: '/team/level-1',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamDirectRoute = AppTeamDirectRouteImport.update({
  id: '/team/direct',
  path: '/team/direct',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryTeamRoute = AppHistoryTeamRouteImport.update({
  id: '/history/team',
  path: '/history/team',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryPassiveRoute = AppHistoryPassiveRouteImport.update({
  id: '/history/passive',
  path: '/history/passive',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryDirectRoute = AppHistoryDirectRouteImport.update({
  id: '/history/direct',
  path: '/history/direct',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai-robot': typeof AppAiRobotRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/': typeof AppIndexRoute
  '/app/history/direct': typeof AppHistoryDirectRoute
  '/app/history/passive': typeof AppHistoryPassiveRoute
  '/app/history/team': typeof AppHistoryTeamRoute
  '/app/team/direct': typeof AppTeamDirectRoute
  '/app/team/level-1': typeof AppTeamLevel1Route
  '/app/team/level-2': typeof AppTeamLevel2Route
  '/app/team/level-3': typeof AppTeamLevel3Route
  '/app/withdrawal/capital': typeof AppWithdrawalCapitalRoute
  '/app/withdrawal/income': typeof AppWithdrawalIncomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai-robot': typeof AppAiRobotRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/salary': typeof AppSalaryRoute
  '/app': typeof AppIndexRoute
  '/app/history/direct': typeof AppHistoryDirectRoute
  '/app/history/passive': typeof AppHistoryPassiveRoute
  '/app/history/team': typeof AppHistoryTeamRoute
  '/app/team/direct': typeof AppTeamDirectRoute
  '/app/team/level-1': typeof AppTeamLevel1Route
  '/app/team/level-2': typeof AppTeamLevel2Route
  '/app/team/level-3': typeof AppTeamLevel3Route
  '/app/withdrawal/capital': typeof AppWithdrawalCapitalRoute
  '/app/withdrawal/income': typeof AppWithdrawalIncomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ai-robot': typeof AppAiRobotRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/': typeof AppIndexRoute
  '/app/history/direct': typeof AppHistoryDirectRoute
  '/app/history/passive': typeof AppHistoryPassiveRoute
  '/app/history/team': typeof AppHistoryTeamRoute
  '/app/team/direct': typeof AppTeamDirectRoute
  '/app/team/level-1': typeof AppTeamLevel1Route
  '/app/team/level-2': typeof AppTeamLevel2Route
  '/app/team/level-3': typeof AppTeamLevel3Route
  '/app/withdrawal/capital': typeof AppWithdrawalCapitalRoute
  '/app/withdrawal/income': typeof AppWithdrawalIncomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai-robot'
    | '/app/notifications'
    | '/app/packages'
    | '/app/profile'
    | '/app/salary'
    | '/app/'
    | '/app/history/direct'
    | '/app/history/passive'
    | '/app/history/team'
    | '/app/team/direct'
    | '/app/team/level-1'
    | '/app/team/level-2'
    | '/app/team/level-3'
    | '/app/withdrawal/capital'
    | '/app/withdrawal/income'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai-robot'
    | '/app/notifications'
    | '/app/packages'
    | '/app/profile'
    | '/app/salary'
    | '/app'
    | '/app/history/direct'
    | '/app/history/passive'
    | '/app/history/team'
    | '/app/team/direct'
    | '/app/team/level-1'
    | '/app/team/level-2'
    | '/app/team/level-3'
    | '/app/withdrawal/capital'
    | '/app/withdrawal/income'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/ai-robot'
    | '/app/notifications'
    | '/app/packages'
    | '/app/profile'
    | '/app/salary'
    | '/app/'
    | '/app/history/direct'
    | '/app/history/passive'
    | '/app/history/team'
    | '/app/team/direct'
    | '/app/team/level-1'
    | '/app/team/level-2'
    | '/app/team/level-3'
    | '/app/withdrawal/capital'
    | '/app/withdrawal/income'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salary': {
      id: '/app/salary'
      path: '/salary'
      fullPath: '/app/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-robot': {
      id: '/app/ai-robot'
      path: '/ai-robot'
      fullPath: '/app/ai-robot'
      preLoaderRoute: typeof AppAiRobotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdrawal/income': {
      id: '/app/withdrawal/income'
      path: '/withdrawal/income'
      fullPath: '/app/withdrawal/income'
      preLoaderRoute: typeof AppWithdrawalIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdrawal/capital': {
      id: '/app/withdrawal/capital'
      path: '/withdrawal/capital'
      fullPath: '/app/withdrawal/capital'
      preLoaderRoute: typeof AppWithdrawalCapitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/level-3': {
      id: '/app/team/level-3'
      path: '/team/level-3'
      fullPath: '/app/team/level-3'
      preLoaderRoute: typeof AppTeamLevel3RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/level-2': {
      id: '/app/team/level-2'
      path: '/team/level-2'
      fullPath: '/app/team/level-2'
      preLoaderRoute: typeof AppTeamLevel2RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/level-1': {
      id: '/app/team/level-1'
      path: '/team/level-1'
      fullPath: '/app/team/level-1'
      preLoaderRoute: typeof AppTeamLevel1RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/direct': {
      id: '/app/team/direct'
      path: '/team/direct'
      fullPath: '/app/team/direct'
      preLoaderRoute: typeof AppTeamDirectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/team': {
      id: '/app/history/team'
      path: '/history/team'
      fullPath: '/app/history/team'
      preLoaderRoute: typeof AppHistoryTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/passive': {
      id: '/app/history/passive'
      path: '/history/passive'
      fullPath: '/app/history/passive'
      preLoaderRoute: typeof AppHistoryPassiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/direct': {
      id: '/app/history/direct'
      path: '/history/direct'
      fullPath: '/app/history/direct'
      preLoaderRoute: typeof AppHistoryDirectRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRobotRoute: typeof AppAiRobotRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHistoryDirectRoute: typeof AppHistoryDirectRoute
  AppHistoryPassiveRoute: typeof AppHistoryPassiveRoute
  AppHistoryTeamRoute: typeof AppHistoryTeamRoute
  AppTeamDirectRoute: typeof AppTeamDirectRoute
  AppTeamLevel1Route: typeof AppTeamLevel1Route
  AppTeamLevel2Route: typeof AppTeamLevel2Route
  AppTeamLevel3Route: typeof AppTeamLevel3Route
  AppWithdrawalCapitalRoute: typeof AppWithdrawalCapitalRoute
  AppWithdrawalIncomeRoute: typeof AppWithdrawalIncomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRobotRoute: AppAiRobotRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppIndexRoute: AppIndexRoute,
  AppHistoryDirectRoute: AppHistoryDirectRoute,
  AppHistoryPassiveRoute: AppHistoryPassiveRoute,
  AppHistoryTeamRoute: AppHistoryTeamRoute,
  AppTeamDirectRoute: AppTeamDirectRoute,
  AppTeamLevel1Route: AppTeamLevel1Route,
  AppTeamLevel2Route: AppTeamLevel2Route,
  AppTeamLevel3Route: AppTeamLevel3Route,
  AppWithdrawalCapitalRoute: AppWithdrawalCapitalRoute,
  AppWithdrawalIncomeRoute: AppWithdrawalIncomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
